language: android
sudo: required
dist: trusty
android:
  components:
    - platform-tools
    - tools
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
licenses:
  - android-sdk-preview-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+
before_script:
  - chmod +x gradlew
stages:
  - name: danger scan
    if: type == pull_request
jobs:
  include:
    - stage: danger scan
      script:
        - "./gradlew assembleDebug"
branches:
  only:
    - master
    - develop
    - "/^feature\\/.*$/"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - "$HOME/.android/build-cache"